### PR TITLE
server: Log responses and errors

### PR DESCRIPTION
**Pull request by radeksimko**
I feel this would be useful in debugging.

Alternatively - if this for any reason doesn't look right - I'm also open to the idea of adding a callback function to `ServerOptions` which would be called between invocation and dispatch, if it's not nil.

### CODE REVIEW

**Comment by creachadair** [comment]
I used to do this, but it was a lot of data. I considered adding log verbosity levels, but that seemed like overkill for debugging. That said, I'm not opposed to the idea, and maybe hooks are (as you suggest) a way to get at it. 

If we are going to go that route I'd be inclined to make a callback (or a pair of them) rather than a log function: One call when the request is received (given the `*Request`), and one when the request is finished processing. (given the `*Response`).

The only obvious problem with b4e9f29 is that it marshals the result regardless of whether the log is wired up to anything. As much as possible, we should avoid doing expensive work (allocating, encoding, etc.) solely for the purpose of logging, unless we know it's needed. (There may be other places where I've violated that principle, but I tried to avoid it)

**Comment by creachadair** [comment]
I'm playing around with a couple of ways to do this. For your purposes, when logging responses: Is it more useful to have the literal JSON payloads that the server sends to the client, or would you rather see `*jrpc2.Response` values matching what the client will observe?

**Comment by radeksimko** [comment]
I think the literal payloads is what I'd be mostly interested in, but technically they are subset of the `*jrpc2.Response`, so that works just as well and perhaps even better aligns with the existing logging of requests.

I had a scenario where a handler was returning an error, but I didn't realize until much later - so maybe adding at least hard-coded error logging would be useful and then leave the "expensive" response logging as "opt-in" via a hook?

**Comment by creachadair** [comment]
> I think the literal payloads is what I'd be mostly interested in, but technically they are subset of the `*jrpc2.Response`, so that works just as well and perhaps even better aligns with the existing logging of requests.

I ask because there are a couple of differences worth noting:

- A `*jrpc2.Response` represents a single response, even if that request is part of a batch. All the responses in a batch are encoded in a single send to the client, once the batch is complete.
- The response value has the ID and the result/error, but is not actually encoded in protocol form. To log it, you'd have to marshal it explicitly.

This means if we pass responses to a callback one by one, the callback can receive them as they complete; but the result will not look like what gets sent to the client (the batch wrapper and the response's order in that wrapper are lost). On the other hand if we pass the encoded message the callback sees the exact output, but will not be called till the whole batch completes. And if the callback wants to examine a single response in the batch, it would have to re-parse the whole thing.

> I had a scenario where a handler was returning an error, but I didn't realize until much later - so maybe adding at least hard-coded error logging would be useful and then leave the "expensive" response logging as "opt-in" via a hook?

That's also an option. Are you interested mainly in a debug view of the error (i.e., the Go error value) or is the JSON encoding important?

**Comment by creachadair** [comment]
I drafted https://github.com/creachadair/jrpc2/pull/9 to demonstrate the one-by-one approach.

**Comment by radeksimko** [comment]
Addressed in https://github.com/creachadair/jrpc2/pull/9

**Pull request closed without merging**
